export 'package:carousel_slider/carousel_slider.dart';
export 'package:flutter/material.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:spotify_clone/common/helpers/is_dark_mode.dart';
export 'package:spotify_clone/common/widgets/appbar/app_bar.dart';
export 'package:spotify_clone/core/configs/assets/app_images.dart';
export 'package:spotify_clone/core/configs/assets/app_vectors.dart';
export 'package:spotify_clone/core/configs/theme/app_colors.dart';
export 'package:spotify_clone/main.dart';
export 'package:spotify_clone/presentation/home/widgets/news_songs.dart';
export 'package:spotify_clone/presentation/home/widgets/all_song.dart';
export 'package:spotify_clone/presentation/profile/pages/profile.dart';
export 'package:flutter/foundation.dart';
// export 'package:flutter/material.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
// export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:hydrated_bloc/hydrated_bloc.dart';
export 'package:path_provider/path_provider.dart';
export 'package:spotify_clone/core/configs/constants/app_key.dart';
export 'package:spotify_clone/core/configs/theme/app_theme.dart';
export 'package:spotify_clone/presentation/choose_mode/bloc/theme_cubit.dart';
export 'package:spotify_clone/presentation/splash/pages/splash.dart';
export 'package:spotify_clone/service_locator.dart';
export 'package:supabase_flutter/supabase_flutter.dart';
